"""empty message

Revision ID: 0f866f0bca00
Revises: e0de75e1a369
Create Date: 2020-11-21 17:32:11.555944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f866f0bca00'
down_revision = 'e0de75e1a369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('register_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'register_date')
    # ### end Alembic commands ###
