"""empty message

Revision ID: d6ed45f0c01b
Revises: 0dff49d5b816
Create Date: 2020-11-22 03:11:46.132158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ed45f0c01b'
down_revision = '0dff49d5b816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('time', sa.Interval(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posiciones')
    # ### end Alembic commands ###
